### ISSUE TITLE
Generated tests can exceed allowed constructor size for GenericMatchers

### ISSUE THREAD

**Issue by maxbechtold** [almondtools/testrecorder#16]
Apparently Java has a size limit for constructors which can be exceeded by testrecorder.

Instrumenting test & Snapshot method
```java
@Test
public void test() {
	Random random = new Random(0);

	new RealisticLandProvider().initialize(120, 240, random);
}
```

```java

class RealisticLandProvider {
	private Set<Integer> index;
	private List<Integer> todo;
	private boolean[][] land;

	@Snapshot
	void initialize(int height, int width, Random rand) {
		...
		index = new TreeSet<>();
		todo = new LinkedList<>();
		land = new boolean[height][width];
		...
	}
}
```

The generated test is too long to post, but yields the error "The code of constructor x() is exceeding the 65535 bytes limit" on the GenericMatcher created for RealisticLandProvider, obviously due to the large 2-dimensional array.

Context: Eclipse Neon, testrecorder 0.2.11-SNAPSHOT [6fb1196]

**Comment by almondtools** [comment]
I can imagine the problem occuring with large arrays. Please correct me if I am wrong:
- the snapshot should work with long arrays
- the test generation should also work with long arrays
- but the generated tests are invalid java classes (because of to much code in one class/constructor/method)

Yet I do not know how to provide a generic solution for this problem. Following approaches come into my mind:
- distributing initialization of array among different helper function (is not generic, because function code and function number is limited too)
- serializing large arrays to files and reading them in the constructor (is generic for primitive arrays, but hardly pure Java and absolutely not maintainable for large non-primitive arrays)
- initializing only array indizes, that are not default (will probably work in your case since most/all entries should null/0 initially, but is not generic)

Maybe you could give some hints/approaches how to solve it.

**Comment by maxbechtold** [comment]
True, true, and true.

idea 1: you already do this partly with the booleanArrayContaining calls. Outlining these would cut down on the constructor size. Perhaps defining child matchers inline is actually the core problem?
idea 2: might be useful as a fallback mechanism in combination with a check 'if Matcher constructor size > 64k' 
idea 3: might do for some mitigation as well (not in my case though, as I left out the logic that fills the array)

see also http://stackoverflow.com/questions/788787/

**Comment by almondtools** [comment]
Thanks for your hints,

idea 1: I think the idea of outlining will not win on the long way ... The code must be placed somewhere and everywhere it could be placed is limited to a maximum of byte codes.

At this time testrecorder provides the opportunity to plug in your own serializer/deserializer. If you are blocked, you might try out to deserialize arrays with a custom deserializer (note that there must be probably two, one for builder, one for matchers). Such a custom deserializer must be included through a ServiceProvider file (the current defaults can be found [here](https://github.com/almondtools/testrecorder/tree/master/src/main/resources/META-INF/services)).

Unfortunately I yet cannot say how convenient the service providers will do with the agent-jar - I will try this out in some time. The Maven Shade Plugin (which would be needed to assemble an agent) allows to merge service entries with a [ServicesResourceTransformer](http://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html#ServicesResourceTransformer).

**Comment by maxbechtold** [comment]
That is if the size limit is the same for all places, did you check?
I'm good, I simply use different parameters for a smaller array. 
Very helpful for refactoring a huge cryptic method :)

**Comment by almondtools** [comment]
Methods are limited to the same size, see http://stackoverflow.com/questions/5689798/why-does-java-limit-the-size-of-a-method-to-65535-byte

I think that classes are limited too, but yet cannot find evidence for this. Yet even if classes are not limited in size, the IDEs do not accept classes of larger sizes. I already crashed Eclipse by loading a generated testrecorder test, because it was too large to parse.

**Comment by maxbechtold** [comment]
Another idea is to extract (short-named) variables, which should reduce code size for primitive and String based structures where many values occur repeatedly. 
I don't know if large non-primitive object structures are are common use case anyway.

**Comment by almondtools** [comment]
The unit test for this case (I hope it matches) fails because of two problems:
- code too large (matches your description)
- too many constants (needs larger arrays)

If you test the same with boolean arrays the "to many constants" message will disappear. I will check it, but my first suspect (based on experience with java byte code) is, that creating constants for literals is part of the byte code compilation and thus using short named variables/constants would produce the same or even larger code.

**Comment by almondtools** [comment]
Now I have completed a (yet undocumented) example how to plug in custom deserializers. Have a look at https://github.com/almondtools/testrecorder-custom-extensions .

It contains two deserializers for large int arrays (one for matchers, one for builders). The idea of these serializers is to spill out the array into a file, where it could be read again from the test, thus avoiding to contain the data in the source code/class file. It is not generic (does only work for `int[][]`) and the test is hardly readable, yet perfectly correct.

To try it out:
- clone the project
- run `mvn clean install`, this will create a jar file that may serve as testrecorder agent
- to test it use [`LargeArrays`](https://github.com/almondtools/testrecorder-custom-extensions/blob/master/src/test/java/net/amygdalum/testrecorder/customdeserializers/LargeArrays.java) which is included in the upper project.
  - run this file with the agent, something like `-javaagent:[artifact].jar=net.amygdalum.testrecorder.customdeserializers.AgentConfig`. This will generate the test in `target/generated`
  - run the tests in target generated

If you need help to adapt the example to a boolean array, I could assist.

**Comment by almondtools** [comment]
Probably I will also try out the approach of providing fixtures and assert-matchers via factory methods. Although this approach will not scale (and thus will break with larger arrays) it may have advantages considering the readability of tests.

Yet such a strategy could produce a lot of factory methods (nested objects, multiple tests), therefore a naming clever strategy is needed:
- a good name would include the name of the variable to which the object is assigned/matched
- maybe the id of the test should be included
- and a unique id

**Comment by almondtools** [comment]
I think I found a promising way to solve the problem. In future versions of testrecorder one will be able to annotate classes, fields, method results or params with the `@Hint` annotation. This will provide a custom deserialization of dedicated objects.

I will track this idea in https://github.com/almondtools/testrecorder/issues/23 and close this issue.
